/vis/scene/create

# Create a scene handler for a specific graphics system
# (Edit the next lines(s) to choose another graphics system
/vis/open OGLIX
#/vis/open OGL


# Draw Scene
#
/vis/viewer/set/style surface
/vis/viewer/set/lightsThetaPhi 90 0 deg
#/vis/viewer/set/viewpointThetaPhi 90 90 deg
#/vis/viewer/zoom 1.5
/vis/viewer/set/upVector 0 0 1
/vis/viewer/addCutawayPlane 0 0 0 m 0 1 0
/vis/viewer/set/viewpointVector 0 -1 0
/vis/viewer/zoom 1


#make some special colors
/tracking/storeTrajectory 0
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 1 0.45 0.08 1
/vis/scene/endOfEventAction accumulate

#make a generic generator
/gps/particle neutron 
/gps/position -70.0 0.0 0.0 cm
/gps/pos/type Point
/gps/ang/type iso
/gps/ene/type Arb 
/gps/hist/type arb 
/gps/hist/file sources/pube_skim.dat 
/gps/hist/inter Lin
#/gps/ene/mono 8 MeV

#make a raytrace model
#/vis/rayTracer/eyePosition 1 1 1 m
#/vis/rayTracer/trace



#/CDMS/genericShield/setPosition 100.0 0.0 0.685355 cm
/CDMS/genericShield/setPosition -70.0 0.0 0.0 cm
/CDMS/genericShield/setSize 10.0 10.0 20.0 cm
/CDMS/genericShield/setMat Lead 
/CDMS/detector/activate GPSShielding 
#/CDMS/detector/deactivate Shields
/CDMS/updateGeometry

/run/beamOn 300 
