/gps/particle neutron
/gps/position 0.0 1000 36.6 mm
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 36.65 mm
/gps/pos/radius 50. mm
/gps/pos/halfz 16.65 mm
/gps/ang/type iso
/gps/ene/type Arb
/gps/hist/type arb
#/gps/hist/file sources/pube_skim.dat
/gps/hist/file sources/neutron_capture.dat
/gps/hist/inter Lin


/CDMS/detector/activate Shields
/CDMS/detector/activate IceBox
/CDMS/detector/activate NaIArray
/CDMS/PuBe/doPuBeGammas false

/CDMS/updateGeometry

/run/beamOn 100000
exit